# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 48b4d7df5b8a76335d7645f254cf39630aee3a16fc0badba0078008c03d0acb3cbe190379e604f0016d9066e2257044775a6a2d93994650f7305ba1bb919c225

test:
  secret_key_base: 9ea6d3fcf5dd44153b027e681039af060bc102743639febc97286f2469738e56d6ddccfbf75886efa77e32e5eac36d466b1540ea6b3d23a69a65ed96843b6d63

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
